spring.application.name: echo
spring.jackson.serialization.indent_output: true
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
server.forward-headers-strategy: framework
eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka

#spring.boot.admin.client.url: http://admin:8092/