app.gateway:
  base-path: /app/ms
  routes-url: http://localhost:${server.port}

spring.autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.ManagementSecurityAutoConfiguration

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: db-service
          uri: lb://db
          predicates:
            - Path=${app.gateway.base-path}/db/**
          filters:
            - RewritePath=${app.gateway.base-path}/db, /
        - id: echo-service
          uri: lb://echo
          predicates:
            - Path=${app.gateway.base-path}/echo/**
          filters:
            - RewritePath=${app.gateway.base-path}/echo, /
        - id: ms1
          uri: lb://ms1
          predicates:
            - Path=${app.gateway.base-path}/ms1/**
          filters:
            - RewritePath=${app.gateway.base-path}/ms1, /

#            - StripPrefix=3
#        - id: eureka-admin
#          uri: lb://eureka/
#          predicates:
#            - Path=${app.gateway.base-path}/eureka/**
#          filters:
#            - StripPrefix=1

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    hostname: localhost
#    prefer-ip-address: true

logging:
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg"
  file.name: spring.log
  file.path: .logs
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty.http.client: debug

management:
  endpoints.web:
    exposure.include: '*'
    based-path: ${app.gateway.base-path}/actuator
  endpoint.health:show-details: always
  info.git.mode: full
  
spring.cloud.gateway.httpserver.wiretap: true
spring.cloud.gateway.httpclient.wiretap: true

spring.main.web-application-type: REACTIVE

spring.output.ansi.enabled: always

#logging.logstash:
#  enabled: true
#  url: logstash:9600
