version: "3"

services:
  eureka:
    image: eureka-server
    container_name: eureka-app
    build:
      context: ./spring-boot-eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

#  eureka:
#    image: jhipster/jhipster-registry
#    ports:
#      - "8761:8761"
#    environment:
#      SPRING_SECURITY_USER_PASSWORD: admin
      
  echo:
    image: echo-app
    container_name: echo-app
    restart: on-failure
    build:
      context: ./spring-boot-echo-service
      dockerfile: Dockerfile
    depends_on:
      - eureka
    entrypoint: ["./wait.sh"]

  ms1:
    image: spring-boot-ms1
    container_name: ms1-app
    restart: on-failure
    build:
      context: ./spring-boot-ms1
      dockerfile: Dockerfile
    depends_on:
      - eureka
    entrypoint: ["./dockertools/wait.sh"]

  admin:
    build: ./spring-boot-admin
    container_name: admin-app
    ports:
      - "8092:8092"
    environment:
      - REGISTRY_HOST=eureka
      - REGISTRY_PORT=8761
    tty:
      true
    restart:
      unless-stopped
#    environment:
#      - EUREKA_SERVICE_URL=http://eureka:8761
#      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
#      - LOGGING_FILE=/tmp/admin.log

  config:
    image: springcloud/configserver
    container_name: config
    depends_on:
      - eureka
    ports:
      - "8888:8888"
#    networks:
#      - "discovery"
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      
  gw:
    image: gw-app
    container_name: gw-app
    restart: on-failure
    build:
      context: ./spring-cloud-gateway
      dockerfile: Dockerfile
    depends_on:
      - eureka
    ports:
      - "10000:8080"
    volumes:
      - ./.logs:/logs/
    entrypoint: ["./dockertools/wait.sh"]

  db-svc:
    image: db-app
    container_name: db-app
    restart: on-failure
    build:
      context: ./spring-boot-db-service
      dockerfile: Dockerfile
    depends_on:
      - eureka
      - db
    entrypoint: ["./wait.sh"]

  db:
    image: mysql:8.0.21
    ports:
      - "33000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  elasticsearch:
    image: elasticsearch:7.16.1
    ports: 
    - "9200:9200"
    - "9300:9300"
    environment:
    - discovery.type=single-node
  kibana:
    image: kibana:7.16.1
    ports:
    - "5601:5601"
    links:
    - elasticsearch
    depends_on:
    - elasticsearch
  logstash:
    image: logstash:7.16.1
    links:
    - elasticsearch
    ports:
    - "9600:9600"
    - "8089:8089"
    volumes:
    - ./conf/:/config-dir
    command: logstash -f /config-dir/logstash.conf
    depends_on:
    - elasticsearch

  nginx: 
    image: nginx:latest
    container_name: nginx-gw
    depends_on:
      - gw
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 20000:80
  