spring.application.name: db-service
spring.jackson.serialization.indent_output: true
server.forward-headers-strategy: framework
eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
spring.jpa.hibernate.ddl.auto: none
spring.datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db/roytuts
    username: root
    password: root