spring.application.name: ms1
springdoc.writer-with-default-pretty-printer: true
spring.jackson.serialization.indent_output: true
eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
server.forward-headers-strategy: framework
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always